---
ID: "484f7d3c-27b0-4fbe-93b4-19900d5e9941"
Parent: "c285a44c-3136-42de-8b34-589d33f6f8e3"
Template: "c285a44c-3136-42de-8b34-589d33f6f8e3"
Path: /sitecore/templates/Feature/Slider/Components/__Standard Values
DB: master
SharedFields:
- ID: "a791f095-2521-4b4d-bef9-21dda221f608"
  Hint: __Style
  Value: |
    color:#AAAAAA;
    font-style:italic;
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191010T112558Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
